### PR TITLE
feat: add ukrainian localization

### PR DESCRIPTION
**Pull request by Oleksey-Korolenko**

### CODE REVIEW

**Comment by chochem** [comment]
from what I understand we are not actually using the repo for anything (but testing). The correct place to PR a change would be https://github.com/Vexatos/TinkersGregworks/tree/GT-NH

**Comment by Dream-Master** [comment]
Yes we use not master

**Review by LewisSaber — APPROVED** [review]

**Comment by Dream-Master** [comment]
i merge it already to master

**Comment by Dream-Master** [comment]
@Oleksey-Korolenko @LewisSaber

**Pull request closed without merging**
