### PR TITLE
use the mLocalizedName

### PR DESCRIPTION
**Pull request by iouter**
can display the localized text now

### CODE REVIEW

**Comment by Dream-Master** [comment]
@iouter can you push the fix to vexatos repo he bake a version for us

**Comment by iouter** [comment]
https://github.com/Vexatos/TinkersGregworks/pull/49

**Comment by Dream-Master** [comment]
@iouter please merge not us master into vexatos he not use us buildscript. Just push only the code changes.

**Comment by iouter** [comment]
sry, that's new pr https://github.com/Vexatos/TinkersGregworks/pull/50

**Pull request merged**
