### PR TITLE
Changed shardcast to IPattern so it can be placed in the pattern chest

### PR DESCRIPTION
**Pull request by PolkageistHS**
Resolution for issue #8774 re: shard cast

### CODE REVIEW

**Review by Glease — APPROVED** [review]
Looking  good. +1 for copying over all the localizations.

**Comment by Dream-Master** [comment]
@PolkageistHS can you doing this integration for the core mod as well ? 
image
image

**Comment by PolkageistHS** [comment]
Yup, I just need to figure out where the `BowFletchingCast(new ModSimpleBaseItem("BowFletchingCast", ModTabList.ModMoldsTab))` enum/function creates the local variable so I can replace it with the IPattern variable.  I'm still fighting with the build.gradle dependencies in the coremod so I can load it in a dev client and be able to view the variables and whatnot.

**Comment by Dream-Master** [comment]
Ok. Hope you get it working

**Pull request merged**
